export const doctorsDB = [
    {
        id: 1,
        name: "Dr. Anjali Kumar",
        degree: "MBBS, MD - Obstetrics & Gynaecology",
        type: "Gynecologist",
        clinic: "Cloudnine Hospital",
        contact: "+91 80 4015 4015",
        address: "15/3, 3rd Block, Jayanagar, Bengaluru, Karnataka 560011",
        pinCode: "560011",
        lat: 12.9299,
        lon: 77.5824,
        gmapsLink: "https://maps.google.com/?q=Cloudnine+Hospital+Jayanagar+Bangalore"
    },
    {
        id: 2,
        name: "Dr. Ramesh Menon",
        degree: "MBBS, DM - Endocrinology",
        type: "Endocrinologist",
        clinic: "Apollo Hospitals",
        contact: "+91 80 2630 4050",
        address: "154/11, Bannerghatta Road, Opp. IIM, Bengaluru, Karnataka 560076",
        pinCode: "560076",
        lat: 12.8955,
        lon: 77.5980,
        gmapsLink: "https://maps.google.com/?q=Apollo+Hospitals+Bannerghatta+Bangalore"
    },
    {
        id: 3,
        name: "Dr. Priya Sharma",
        degree: "MBBS, MD - General Medicine",
        type: "General Physician",
        clinic: "Manipal Hospital",
        contact: "+91 80 2521 1200",
        address: "98, HAL Old Airport Rd, Kodihalli, Bengaluru, Karnataka 560017",
        pinCode: "560017",
        lat: 12.9592,
        lon: 77.6481,
        gmapsLink: "https://maps.google.com/?q=Manipal+Hospital+Old+Airport+Road+Bangalore"
    },
    {
        id: 4,
        name: "Dr. Sushma Reddy",
        degree: "MBBS, MS - Obstetrics & Gynaecology",
        type: "Gynecologist",
        clinic: "Motherhood Hospital",
        contact: "+91 80 6723 8833",
        address: "324, 100 Feet Rd, Indiranagar 1st Stage, Bengaluru, Karnataka 560038",
        pinCode: "560038",
        lat: 12.9719,
        lon: 77.6412,
        gmapsLink: "https://maps.google.com/?q=Motherhood+Hospital+Indiranagar+Bangalore"
    },
    {
        id: 5,
        name: "Dr. Arvind Shetty",
        degree: "MBBS, MD - General Medicine",
        type: "General Physician",
        clinic: "Fortis Hospital",
        contact: "+91 80 6621 4444",
        address: "154/9, Bannerghatta Road, Opposite IIM-B, Bengaluru, Karnataka 560076",
        pinCode: "560076",
        lat: 12.8942,
        lon: 77.5975,
        gmapsLink: "https://maps.google.com/?q=Fortis+Hospital+Bannerghatta+Bangalore"
    },
    {
        id: 6,
        name: "Dr. Shalini Rao",
        degree: "MBBS, DM - Endocrinology",
        type: "Endocrinologist",
        clinic: "Aster CMI Hospital",
        contact: "+91 80 4342 0100",
        address: "43/2, New Airport Road, NH-44, Sahakar Nagar, Bengaluru, Karnataka 560092",
        pinCode: "560092",
        lat: 13.0535,
        lon: 77.5950,
        gmapsLink: "https://maps.google.com/?q=Aster+CMI+Hospital+Hebbal+Bangalore"
    },
    {
        id: 7,
        name: "Dr. Rajesh K",
        degree: "MBBS, MD - General Medicine",
        type: "General Physician",
        clinic: "RxDx Healthcare",
        contact: "+91 80 4926 1111",
        address: "29, 11th Main Rd, Malleshwaram, Bengaluru, Karnataka 560003",
        pinCode: "560003",
        lat: 13.0031,
        lon: 77.5643,
        gmapsLink: "https://maps.google.com/?q=RxDx+Healthcare+Malleshwaram+Bangalore"
    },
    {
        id: 8,
        name: "Dr. Anita Desai",
        degree: "MBBS, MS - Obstetrics & Gynaecology",
        type: "Gynecologist",
        clinic: "Sakra World Hospital",
        contact: "+91 80 4969 4969",
        address: "SY NO 52/2 & 52/3, Devarabeesanahalli Varthur Hobli, Bengaluru, Karnataka 560103",
        pinCode: "560103",
        lat: 12.9322,
        lon: 77.6845,
        gmapsLink: "https://maps.google.com/?q=Sakra+World+Hospital+Bellandur+Bangalore"
    },
    {
        id: 9,
        name: "Dr. Vikram Patel",
        degree: "MBBS, DM - Endocrinology",
        type: "Endocrinologist",
        clinic: "Narayana Multispeciality Hospital",
        contact: "+91 80 7122 2222",
        address: "Behind Narayana Hrudayalaya, Bommasandra Industrial Area, Bengaluru, Karnataka 560099",
        pinCode: "560099",
        lat: 12.8164,
        lon: 77.6830,
        gmapsLink: "https://maps.google.com/?q=Narayana+Multispeciality+Hospital+Bommasandra"
    },
    {
        id: 10,
        name: "Dr. Lakshmi N",
        degree: "MBBS, MD - Obstetrics & Gynaecology",
        type: "Gynecologist",
        clinic: "Columbia Asia Hospital (Manipal)",
        contact: "+91 80 4172 0920",
        address: "Koramangala 3rd Block, Sarjapur Main Rd, Bengaluru, Karnataka 560034",
        pinCode: "560034",
        lat: 12.9298,
        lon: 77.6322,
        gmapsLink: "https://maps.google.com/?q=Columbia+Asia+Hospital+Koramangala+Bangalore"
    },
    {
        id: 11,
        name: "Dr. Ravi Shankar",
        degree: "MBBS, MD - General Medicine",
        type: "General Physician",
        clinic: "Sparsh Hospital",
        contact: "+91 80 6122 2000",
        address: "146, Infantry Road, Vasanth Nagar, Bengaluru, Karnataka 560001",
        pinCode: "560001",
        lat: 12.9830,
        lon: 77.5960,
        gmapsLink: "https://maps.google.com/?q=Sparsh+Hospital+Infantry+Road+Bangalore"
    },
    {
        id: 12,
        name: "Dr. Sunita Varma",
        degree: "MBBS, DM - Endocrinology",
        type: "Endocrinologist",
        clinic: "BGS Gleneagles Global Hospital",
        contact: "+91 80 2625 2525",
        address: "67, Uttarahalli Road, Kengeri, Bengaluru, Karnataka 560060",
        pinCode: "560060",
        lat: 12.9036,
        lon: 77.4988,
        gmapsLink: "https://maps.google.com/?q=BGS+Gleneagles+Global+Hospital+Kengeri"
    },
    {
        id: 13,
        name: "Dr. Rekha M",
        degree: "MBBS, MS - Obstetrics & Gynaecology",
        type: "Gynecologist",
        clinic: "Manipal Hospital Whitefield",
        contact: "+91 80 6165 6666",
        address: "143, 212-2015, KR Puram Hobli, Whitefield, Bengaluru, Karnataka 560066",
        pinCode: "560066",
        lat: 12.9698,
        lon: 77.7499,
        gmapsLink: "https://maps.google.com/?q=Manipal+Hospital+Whitefield+Bangalore"
    },
    {
        id: 14,
        name: "Dr. Anand K",
        degree: "MBBS, MD - General Medicine",
        type: "General Physician",
        clinic: "Vikram Hospital",
        contact: "+91 80 7100 4500",
        address: "71/1, Millers Rd, Vasanth Nagar, Bengaluru, Karnataka 560052",
        pinCode: "560052",
        lat: 12.9890,
        lon: 77.5950,
        gmapsLink: "https://maps.google.com/?q=Vikram+Hospital+Millers+Road+Bangalore"
    },
    {
        id: 15,
        name: "Dr. Deepak P",
        degree: "MBBS, MD - General Medicine",
        type: "General Physician",
        clinic: "Vydehi Institute of Medical Sciences",
        contact: "+91 80 2841 3381",
        address: "82, Nallurahalli Main Rd, Whitefield, Bengaluru, Karnataka 560066",
        pinCode: "560066",
        lat: 12.9723,
        lon: 77.7288,
        gmapsLink: "https://maps.google.com/?q=Vydehi+Institute+of+Medical+Sciences+Whitefield"
    },
    {
        id: 16,
        name: "Dr. Suresh K",
        degree: "MBBS",
        type: "General Physician",
        clinic: "Sri Sai Care Clinic",
        contact: "+91 99001 12345",
        address: "34, Devarachikkanahalli Main Rd, Bommanahalli, Bengaluru, Karnataka 560068",
        pinCode: "560068",
        lat: 12.9020,
        lon: 77.6210,
        gmapsLink: "https://maps.google.com/?q=Bommanahalli+Bangalore+Clinic"
    },
    {
        id: 17,
        name: "Dr. Meena R",
        degree: "MBBS, DGO",
        type: "Gynecologist",
        clinic: "Mathru Health Clinic",
        contact: "+91 98888 23456",
        address: "12, 1st Cross, Hongasandra, Begur Road, Bengaluru, Karnataka 560068",
        pinCode: "560068",
        lat: 12.9055,
        lon: 77.6241,
        gmapsLink: "https://maps.google.com/?q=Hongasandra+Bangalore+Clinic"
    },
    {
        id: 18,
        name: "Dr. Kishore Kumar",
        degree: "MBBS, MD - General Medicine",
        type: "General Physician",
        clinic: "Bommanahalli Family Clinic",
        contact: "+91 80 2573 9999",
        address: "Site 56, Hosur Rd, near Bommanahalli Signal, Bengaluru, Karnataka 560068",
        pinCode: "560068",
        lat: 12.8990,
        lon: 77.6200,
        gmapsLink: "https://maps.google.com/?q=Hosur+Road+Bommanahalli+Clinic"
    },
    {
        id: 19,
        name: "Dr. Asha Reddy",
        degree: "MBBS, MS - Obstetrics & Gynaecology",
        type: "Gynecologist",
        clinic: "Sanjeevini Poly Clinic",
        contact: "+91 91234 56789",
        address: "99, Garvebhavipalya, Hosur Road, Bengaluru, Karnataka 560068",
        pinCode: "560068",
        lat: 12.9075,
        lon: 77.6290,
        gmapsLink: "https://maps.google.com/?q=Garvebhavipalya+Bangalore"
    },
    {
        id: 20,
        name: "Dr. Karthik S",
        degree: "MBBS, MD - Internal Medicine",
        type: "Endocrinologist",
        clinic: "LifeCare Hormone Clinic",
        contact: "+91 80 4321 8765",
        address: "4th Main, Roopena Agrahara, Bommanahalli, Bengaluru, Karnataka 560068",
        pinCode: "560068",
        lat: 12.9030,
        lon: 77.6250,
        gmapsLink: "https://maps.google.com/?q=Roopena+Agrahara+Bangalore"
    },
    {
        id: 21,
        name: "Dr. Vishwa Vijeth",
        degree: "MBBS, MD - Pulmonary Medicine",
        type: "General Physician",
        clinic: "Praapthi Chest and Women Clinic",
        contact: "+91 89047 50743",
        address: "Building No-681, 22nd Cross, 2nd Sector, HSR Layout, Bengaluru, Karnataka 560102",
        pinCode: "560102",
        lat: 12.9121,
        lon: 77.6446,
        gmapsLink: "https://maps.google.com/?q=Praapthi+Chest+and+Women+Clinic+HSR+Layout"
    },
    {
        id: 22,
        name: "Dr. Shilpa V",
        degree: "MBBS, MS - Obstetrics & Gynaecology",
        type: "Gynecologist",
        clinic: "Praapthi Chest and Women Clinic",
        contact: "+91 89047 50743",
        address: "Building No-681, 22nd Cross, 2nd Sector, HSR Layout, Bengaluru, Karnataka 560102",
        pinCode: "560102",
        lat: 12.9121,
        lon: 77.6446,
        gmapsLink: "https://maps.google.com/?q=Praapthi+Chest+and+Women+Clinic+HSR+Layout"
    },
    {
        id: 23,
        name: "Dr. Poornima N",
        degree: "MBBS, DGO",
        type: "Gynecologist",
        clinic: "Narayana Multispeciality Clinic HSR",
        contact: "+91 80 7111 2222",
        address: "24th Main Road, Agara, 1st Sector, HSR Layout, Bengaluru, Karnataka 560102",
        pinCode: "560102",
        lat: 12.9180,
        lon: 77.6405,
        gmapsLink: "https://maps.google.com/?q=Narayana+Clinic+HSR+Layout"
    },
    {
        id: 24,
        name: "Dr. Srinivas Bharadwaj",
        degree: "MBBS, MD",
        type: "General Physician",
        clinic: "HSR Family Health Clinic",
        contact: "+91 80 2222 3333",
        address: "17th Cross, 4th Sector, HSR Layout, Bengaluru, Karnataka 560102",
        pinCode: "560102",
        lat: 12.9100,
        lon: 77.6350,
        gmapsLink: "https://maps.google.com/?q=HSR+Layout+Bangalore"
    },
    {
        id: 25,
        name: "Dr. Rashmi C",
        degree: "MBBS, DM - Endocrinology",
        type: "Endocrinologist",
        clinic: "Apollo Clinic HSR",
        contact: "+91 80 4444 5555",
        address: "Sector 3, HSR Layout, Bengaluru, Karnataka 560102",
        pinCode: "560102",
        lat: 12.9085,
        lon: 77.6480,
        gmapsLink: "https://maps.google.com/?q=Apollo+Clinic+HSR+Layout"
    },
    {
        id: 26,
        name: "Dr. Naveen Kumar",
        degree: "MBBS, MD - General Medicine",
        type: "General Physician",
        clinic: "CureHub Polyclinic",
        contact: "+91 99002 23344",
        address: "19th Main, 1st Sector, HSR Layout, Bengaluru, Karnataka 560102",
        pinCode: "560102",
        lat: 12.9155,
        lon: 77.6420,
        gmapsLink: "https://maps.google.com/?q=CureHub+Polyclinic+HSR"
    },
    {
        id: 27,
        name: "Dr. Radhika Iyer",
        degree: "MBBS, DGO",
        type: "Gynecologist",
        clinic: "LifeSpring Mother & Care",
        contact: "+91 98888 77777",
        address: "2nd Sector, HSR Layout, Bengaluru, Karnataka 560102",
        pinCode: "560102",
        lat: 12.9130,
        lon: 77.6455,
        gmapsLink: "https://maps.google.com/?q=HSR+Layout+Bangalore"
    },
    {
        id: 28,
        name: "Dr. Suguna Reddy",
        degree: "MBBS, MD - Obstetrics & Gynaecology",
        type: "Gynecologist",
        clinic: "Lake View Hospital / Apollo Clinic",
        contact: "+91 80 4350 4350",
        address: "22nd Cross, Sector 3, HSR Layout, Bengaluru, Karnataka 560102",
        pinCode: "560102",
        lat: 12.9095,
        lon: 77.6430,
        gmapsLink: "https://maps.google.com/?q=Apollo+Clinic+HSR"
    },
    {
        id: 29,
        name: "Dr. Sunita P Shekokar",
        degree: "MBBS, MD - Obstetrics & Gynaecology",
        type: "Gynecologist",
        clinic: "Birth and Beyond Clinic",
        contact: "+91 99887 66554",
        address: "14th Main Road, Sector 4, HSR Layout, Bengaluru, Karnataka 560102",
        pinCode: "560102",
        lat: 12.9108,
        lon: 77.6360,
        gmapsLink: "https://maps.google.com/?q=Birth+and+Beyond+Clinic+HSR"
    },
    {
        id: 30,
        name: "Dr. Vanita Vaishnav",
        degree: "MBBS, DNB - Obstetrics & Gynaecology",
        type: "Gynecologist",
        clinic: "Apollo Clinic HSR / Narayana",
        contact: "+91 80 4444 5555",
        address: "Sector 3, HSR Layout, Bengaluru, Karnataka 560102",
        pinCode: "560102",
        lat: 12.9085,
        lon: 77.6480,
        gmapsLink: "https://maps.google.com/?q=Apollo+Clinic+HSR+Layout"
    },
    {
        id: 31,
        name: "Dr. Chitra Ramamurthy",
        degree: "MBBS, MD, Infertility Specialist",
        type: "Gynecologist",
        clinic: "Apollo Cradle HSR",
        contact: "+91 80 4050 4050",
        address: "15th Cross Road, Sector 4, HSR Layout, Bengaluru, Karnataka 560102",
        pinCode: "560102",
        lat: 12.9112,
        lon: 77.6385,
        gmapsLink: "https://maps.google.com/?q=Apollo+Cradle+HSR"
    },
    {
        id: 32,
        name: "Dr. Deepa Rajendran",
        degree: "MBBS, MS - Obstetrics & Gynaecology",
        type: "Gynecologist",
        clinic: "Motherhood Hospital HSR",
        contact: "+91 80 6723 8833",
        address: "19th Main, Sector 1, HSR Layout, Bengaluru, Karnataka 560102",
        pinCode: "560102",
        lat: 12.9150,
        lon: 77.6415,
        gmapsLink: "https://maps.google.com/?q=Motherhood+Hospitals+HSR"
    },
    {
        id: 33,
        name: "Dr. Gauthami M",
        degree: "MBBS, DGO, Laparoscopic Surgeon",
        type: "Gynecologist",
        clinic: "Cloudnine Hospital HSR",
        contact: "+91 80 4015 4015",
        address: "17th Cross, Sector 4, HSR Layout, Bengaluru, Karnataka 560102",
        pinCode: "560102",
        lat: 12.9100,
        lon: 77.6350,
        gmapsLink: "https://maps.google.com/?q=Cloudnine+HSR+Layout"
    }
];
